var url=location.href;var titelNews='';if(typeof hauptFarbe=="undefined"){var hauptFarbe='rgb(215, 38, 34)';}
var iframeBreite=window.innerWidth;if(urlTicker!==''){var ticker='<iframe style="width: 100%" src="'+urlTicker+tickerSprache+'&width='+iframeBreite+'" frameborder="0" scrolling="no" height="35"></iframe>';}else{var ticker='';}
var laenderAuswahl='<div class="btn-group divLaender">'+
'<span class="laenderAuswahl">'+waehlenSieEinLand+'</span>'+
'<button class="btn btn-default btn-xs dropdown-toggle buttonFont14" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'+russland+' <span class="caret"></span>'+
'</button>'+
'<ul class="dropdown-menu">'+
'<li><a href="'+urlOesterreich+'">'+oesterreich+'</a></li>'+
'<li><a href="'+urlDeutschland+'">'+deutschland+'</a></li>'+
'<li><a href="'+urlSchweiz+'">'+schweiz+'</a></li>'+
'</ul>'+
'</div>';var hauptNav='<script type="text/javascript" src="'+urlHauptNav+'"></script>';var unterNav='<script type="text/javascript" src="'+urlUnterNav+'"></script>';var claim='<img src="'+claimURL+'" class="img-responsive" />';if(claimURL==''){claim='';}
var jetztBewerben='<a href="'+urlJetztBewerben+'" target="_self" class="linkRot"><img src="https://www.strabag-cdn.net/comp/_images/pfeil_rot.png" style="margin-right: 5px; " class="imgPfeilRot" />'+jetztBewerbenBeschriftung+'</a>';var initiativBewerben='<a href="'+urlInitiativBewerben+'" target="_blank" class="linkRot"><img src="https://www.strabag-cdn.net/comp/_images/pfeil_rot.png" style="margin-right: 5px; " class="imgPfeilRot" />'+initiativBewerbenBeschriftung+'</a>';var suchenImage='<a href="'+urlSuchenImage+'"><img src="'+suchenImage+'" /></a>';if(typeof urlDatenschutz==="undefined"){var urlDatenschutz="http://www.strabag.com/databases/internet/_public/content.nsf/web/DE-STRABAG.COM-datenschutz.html";}
if(typeof textDatenschutz==="undefined"){var textDatenschutz="Datenschutz Erklärung";}
var datenschutz='<a href="'+urlDatenschutz+'"><img src="https://www.strabag-cdn.net/comp/_images/icondatenschutz.gif" /><br />'+textDatenschutz+'</a>';var impressum='<a href="'+urlImpressum+'"><img src="https://www.strabag-cdn.net/comp/_images/iconimpressum.gif" /><br />'+textImpressum+'</a>';var rechtshinweis='<a href="'+urlRechtshinweis+'"><img src="https://www.strabag-cdn.net/comp/_images/iconrecht.gif" /><br />'+textRechtshinweis+'</a>';if(typeof urlRechnungslegung==="string"){var rechnungslegung='<a href="'+urlRechnungslegung+'" /><img src="https://www.strabag-cdn.net/comp/_images/footer-icons/rechnungslegung.png" /><br />'+textRechnungslegung+'</a>';}
var kontakt='<a href="'+urlKontakt+'" /><img src="https://www.strabag-cdn.net/comp/_images/iconkontakt.gif" /><br />'+textKontakt+'</a>';var logo='<a href="#"><img src="'+urlLogo+'" /></a>';var ADRESSE='<div id="adresse" class="minilink">'+textAdresse+'</div>';function macheRequest(requestUrl){var tmp=requestUrl.split("#?id=");var docid=tmp[1];var url=tmp[0];var http_request=false;if(window.XMLHttpRequest){http_request=new XMLHttpRequest();if(http_request.overrideMimeType){http_request.overrideMimeType('text/xml');}}else if(window.ActiveXObject){try{http_request=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{http_request=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){}}}
if(!http_request){alert('Ende :( Kann keine XMLHTTP-Instanz erzeugen');return false;}
http_request.open('GET',url,true);http_request.send(null);alert(http_request.responseText);var content1=http_request.responseText.split("<!-- TRENNER -->");document.getElementById(docid+"box_liste_1").innerHTML=content1[1];document.getElementById(docid+"box_liste_2").innerHTML=content1[2];document.getElementById(docid+"box_liste_3").innerHTML=content1[3];document.getElementById(docid+"box_liste_4").innerHTML=content1[4];}
function macheRequest2(url){http_request=false;if(window.XMLHttpRequest){http_request=new XMLHttpRequest();if(http_request.overrideMimeType){http_request.overrideMimeType('text/xml');}}else if(window.ActiveXObject){try{http_request=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{http_request=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){}}}
if(!http_request){alert('Ende :( Kann keine XMLHTTP-Instanz erzeugen');return false;}
http_request.onreadystatechange=alertInhalt2;http_request.open('GET',url,true);http_request.send(null);}
function boxenladen(){var BOX_1_LISTE_DESCRIPTOR="global";var BOX_2_LISTE_DESCRIPTOR="global";var BOX_3_LISTE_DESCRIPTOR="global";var BOX_4_LISTE_DESCRIPTOR="global";alert(docid);if(http_request.readyState==4){if(http_request.status==200){var content1=http_request.responseText;content1=content1.split("<!-- TRENNER -->");BOX_1_LISTE_DESCRIPTOR=content1[1];BOX_2_LISTE_DESCRIPTOR=content1[2];BOX_3_LISTE_DESCRIPTOR=content1[3];BOX_4_LISTE_DESCRIPTOR=content1[4];var boxliste1=id+'box_liste_1';var boxliste2=id+'box_liste_2';var boxliste3=id+'box_liste_3';var boxliste4=id+'box_liste_4';document.getElementById(boxliste1).innerHTML=BOX_1_LISTE_DESCRIPTOR;document.getElementById(boxliste2).innerHTML=BOX_2_LISTE_DESCRIPTOR;document.getElementById(boxliste3).innerHTML=BOX_3_LISTE_DESCRIPTOR;document.getElementById(boxliste4).innerHTML=BOX_4_LISTE_DESCRIPTOR;}else{alert('Bei dem Request ist ein Problem aufgetreten.');}}}
function alertInhalt1(){if(http_request.readyState==4){if(http_request.status==200){var content1=http_request.responseText;content1=content1.replace('<META HTTP-EQUIV="Refresh" CONTENT="0; URL=../WebPrint?OpenAgent&docid=','');content1=content1.replace('">','');content1="http://karriere.strabag.com/databases/internet/_public/content.nsf/WebPrint?OpenAgent&docid="+content1;content1=content1.replace('&docid= ','&docid=');macheRequest2(content1);}else{alert('Bei dem Request ist ein Problem aufgetreten.');}}}
function alertInhalt2(){if(http_request.readyState==4){if(http_request.status==200){var content=http_request.responseText;document.getElementById('boxen').innerHTML=content;}else{alert('Bei dem Request ist ein Problem aufgetreten.');}}}
function closeInhalt(){var content="";document.getElementById('trans').innerHTML=content;document.getElementById('trans').style.display='none';}
function loadList(requestUrl){var tmp=requestUrl.split("#?id=");$.get(tmp[0],function(data){var list=data.split("<!-- TRENNER -->");var liste_1=list[1].replace(/.pdf" target="_self"/g,'.pdf\" target=\"_blank\"');$("#"+tmp[1]+"_box_liste_1").html(liste_1);$("#"+tmp[1]+"_box_liste_2").html(list[2]);$("#"+tmp[1]+"_box_liste_3").html(list[3]);$("#"+tmp[1]+"_box_liste_4").html(list[4]);});}
function boxStart(requestUrl){var tmp=requestUrl.split("id=");$.get(requestUrl,function(data){var list=data.split("<!-- TRENNER -->");$("#"+tmp[1]+"_box_liste_1").html(list[1]);$("#"+tmp[1]+"_box_liste_2").html(list[2]);$("#"+tmp[1]+"_box_liste_3").html(list[3]);$("#"+tmp[1]+"_box_liste_4").html(list[4]);});}
function loadTab(requestUrl){var tmp=requestUrl.split("#?id=");$.get(tmp[0],function(data){var list=data.split("<!-- TRENNER2 -->");$("#"+tmp[1]).html(list[1]);});}
function loadTab3(requestUrl2){var tmp=requestUrl2.split("**id=");$.get(tmp[0],function(data){var list=data.split("<!-- TRENNER2 -->");$("#"+tmp[1]+"_3").html(list[1]);});}
function loadTabsNew(requestUrl){var tmp=requestUrl.split("#id=");placemarks=[];$(document).ready(function(){$.ajax({type:"GET",async:false,url:"requestUrl",cache:false,data:input,dataType:'json',success:function(data){placemarks=data;alert("hier");},error:function(){alert("sad story...");}});});}
function loadContact(requestUrl){$.get(requestUrl,function(data){var list=data.split("<!-- TRENNER -->");$("#kontakt").html(list[1]);});}
function loadNewsticker(requestUrl){$.get(requestUrl,function(data){var list=data.split("<!-- TRENNER -->");$("#ticker02").html(list[1]);});}
function loadSitemap(requestUrl){$.get(requestUrl,function(data){$("#sitemap").html(data);});}
function loadCSR(requestUrl){$.get(requestUrl,function(data){$("#csrDescription").html(data);});}
function loadTabelle(requestUrl){$("#tabelleninhalt").load(requestUrl,function(){$('#example').dataTable({"bJQueryUI":true,"sPaginationType":"full_numbers","bAutoWidth":false,"aoColumns":[{sWidth:'60%'},{sWidth:'40%'}]});});}
function loadTeaserE(requestUrl){var tmp=requestUrl.split("&id=");$.get(tmp[0],function(data){var list=data.split("<!-- TEASER -->");$("#"+tmp[1]+"_teaser").html(list[1]);});}
function loadPulldown(requestUrl){var tmp=requestUrl.split("#?id=");$.get(tmp[0],function(data){var list=data.split("<!-- TRENNER -->");$("#"+tmp[1]+"_title").html(list[1]);$("#"+tmp[1]+"_td").html(list[2]);});}
(function(){var scrollHandle=0,scrollStep=5,parent=$("#container");$(".panner").on("mousedown",function(){var data=$(this).data('scrollModifier'),direction=parseInt(data,10);$(this).addClass('active');startScrolling(direction,scrollStep);});$(".panner").on("mouseup",function(){stopScrolling();$(this).removeClass('active');});function startScrolling(modifier,step){if(scrollHandle===0){scrollHandle=setInterval(function(){var newOffset=parent.scrollLeft()+(scrollStep*modifier);parent.scrollLeft(newOffset);},10);}}
function stopScrolling(){clearInterval(scrollHandle);scrollHandle=0;}}());window.onscroll=function()
{if(window.XMLHttpRequest){if(document.documentElement.scrollTop>logoScrollTop||self.pageYOffset>logoScrollTop){$('#logoScroll').css('display','block');$('#logoScroll2').css('display','none');}else if(document.documentElement.scrollTop<logoScrollTop||self.pageYOffset<logoScrollTop){$('#logoScroll').css('display','none');$('#logoScroll2').css('display','block');}}};